# Generated by Django 6.0.5 on 2026-05-29 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('company', models.CharField(choices=[('Comnet', 'Comnet'), ('Farbell', 'Farbell'), ('Afrinet', 'Afrinet')], default='Comnet', max_length=50)),
                ('address', models.TextField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StarlinkAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=100, unique=True)),
                ('last_payment_date', models.DateField(blank=True, null=True)),
                ('account_due_by', models.DateField(blank=True, null=True)),
                ('cost_to_us', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('client_invoice', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
            options={
                'ordering': ['account_number'],
            },
        ),
        migrations.CreateModel(
            name='Credential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(default='Starlink Account', max_length=100)),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('email_pass', models.CharField(blank=True, max_length=255, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credentials', to='tracker.starlinkaccount')),
            ],
        ),
        migrations.CreateModel(
            name='StarlinkDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kit_number', models.CharField(max_length=100, unique=True)),
                ('location_name', models.CharField(max_length=255)),
                ('model', models.CharField(choices=[('gen2', 'Gen 2'), ('Mini', 'Mini'), ('Gen3', 'Gen 3')], default='Gen3', max_length=50)),
                ('starlink_id', models.CharField(blank=True, max_length=100, null=True)),
                ('serial_number', models.CharField(blank=True, max_length=100, null=True)),
                ('wifi_name', models.CharField(blank=True, max_length=100, null=True)),
                ('wifi_password', models.CharField(blank=True, max_length=100, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Running', 'Running'), ('To install', 'To install'), ('Deactivated', 'Deactivated'), ('Hardware fault', 'Hardware fault'), ('Account issue', 'Account issue')], default='To install', max_length=50)),
                ('notes', models.TextField(blank=True, null=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='starlinks', to='tracker.starlinkaccount')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='starlinks', to='tracker.client')),
            ],
        ),
    ]
