# Generated by Django 6.0.5 on 2026-06-04 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_auditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='starlinkaccount',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounts', to='tracker.client'),
        ),
    ]
